/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrameUserInterface.OptionsJFrames;

import helperClasses.ScreenSizeClass;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Abdelhalim
 */
public class DateAndTimeJFrame extends javax.swing.JFrame {

    SpinnerModel spinnerHourModel,
            spinnerMinuteModel;
    /**
     * Creates new form DateAndTimeJFrame
     */
    public DateAndTimeJFrame() {
        initComponents();
        this.setLocation(ScreenSizeClass.getWidth(26),
                ScreenSizeClass.getHeight(13));
        this.pack();
        spinnerHourModel = new SpinnerNumberModel(1, 1, 24, 1);
        spinnerMinuteModel = new SpinnerNumberModel(1,1,59,1);
        jSpinnerHours.setModel(spinnerHourModel);
        jSpinnerMinutes.setModel(spinnerMinuteModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelChooseDate = new javax.swing.JLabel();
        jLabelChooseTime = new javax.swing.JLabel();
        jPanelTimeChooser1 = new javax.swing.JPanel();
        jLabelSeconds = new javax.swing.JLabel();
        jLabelMinutes = new javax.swing.JLabel();
        jSpinnerMinutes = new javax.swing.JSpinner();
        jLabelHours = new javax.swing.JLabel();
        jSpinnerHours = new javax.swing.JSpinner();
        jComboBoxTiming = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelSeparator = new javax.swing.JLabel();
        jLabelSeparator1 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Date and Time Chooser");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelChooseDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChooseDate.setText("Choose Task Date");

        jLabelChooseTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChooseTime.setText("Choose Task Time");

        jLabelSeconds.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSeconds.setText("Timing");

        jLabelMinutes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMinutes.setText("Minutes");

        jLabelHours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHours.setText("Hours");

        jComboBoxTiming.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("  :");

        javax.swing.GroupLayout jPanelTimeChooser1Layout = new javax.swing.GroupLayout(jPanelTimeChooser1);
        jPanelTimeChooser1.setLayout(jPanelTimeChooser1Layout);
        jPanelTimeChooser1Layout.setHorizontalGroup(
            jPanelTimeChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTimeChooser1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTimeChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerHours))
                .addGroup(jPanelTimeChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelTimeChooser1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelMinutes))
                    .addGroup(jPanelTimeChooser1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(34, 34, 34)
                .addGroup(jPanelTimeChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTiming, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelTimeChooser1Layout.setVerticalGroup(
            jPanelTimeChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeChooser1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTimeChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeconds)
                    .addComponent(jLabelMinutes)
                    .addComponent(jLabelHours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanelTimeChooser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTiming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabelSeparator.setText("================================================================");

        jLabelSeparator1.setText("================================================================");

        jButtonSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSubmit.setText("Submit Task Date and Time");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelChooseDate))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelSeparator))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelChooseTime)
                .addGap(59, 59, 59)
                .addComponent(jPanelTimeChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jButtonCancel)
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelChooseDate)
                .addGap(269, 269, 269)
                .addComponent(jLabelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelChooseTime))
                    .addComponent(jPanelTimeChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabelSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSubmit)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        /**
         * store date and time
         */
        //java.util.Calendar calendar = jDateChooserPanel1.getSelectedDate();
//        String day = "" + calendar.getTime().getDate();
//        String month = "" + calendar.getTime().getMonth();
//        String year = "" + calendar.getTime().getYear();
//        String hour = jSpinnerHours.getValue().toString();
//        String minute = jSpinnerMinutes.getValue().toString();
//        String timing = jComboBoxTiming.getSelectedItem().toString();
//        System.out.println("   hours = " + hour
//                + "   minutes = " + minute
//                + "   Timing = " + timing);

//        String Time = "" + hour + ":" + minute + "   " + timing;
//        String date = "" + day + "-" + (Integer.parseInt(month) + 1) + "-"
//                + (Integer.parseInt(year) + 1900);
//        
//        System.out.println("   day = " + day
//                + "   month = " + month
//                + "   year = " + (Integer.parseInt(year) + 1900));
//        System.out.println("Date is " + day + "-" + (Integer.parseInt(month) + 1) + "-"
//                + (Integer.parseInt(year) + 1900));
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateAndTimeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateAndTimeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateAndTimeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateAndTimeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DateAndTimeJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox jComboBoxTiming;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChooseDate;
    private javax.swing.JLabel jLabelChooseTime;
    private javax.swing.JLabel jLabelHours;
    private javax.swing.JLabel jLabelMinutes;
    private javax.swing.JLabel jLabelSeconds;
    private javax.swing.JLabel jLabelSeparator;
    private javax.swing.JLabel jLabelSeparator1;
    private javax.swing.JPanel jPanelTimeChooser1;
    private javax.swing.JSpinner jSpinnerHours;
    private javax.swing.JSpinner jSpinnerMinutes;
    // End of variables declaration//GEN-END:variables
}
